### ISSUE TITLE
CSSのリファクタリング

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#102]
main.scssとpages配下のCSSでほとんど内容が重複してしまっている

・全体に必要なものだけをmain.scssに残す
・pagesの方で不要な記述を削除していく

**Comment by YutoMoriyasu** [comment]
- [ ] main.scssからservice.scssを切り離す
- [ ] header, footerの記述を_header.scss, _footer.scssのみに集約する
