### ISSUE TITLE
pagesをsrc配下に移動

### ISSUE THREAD

**Issue by bigdragon0610** [Anti-Pattern-Inc/anti-pattern-inc.github.io#193]
## 背景
srcとpagesが同じ階層にある
<img width="119" alt="スクリーンショット 2023-04-01 19 30 43" src="https://user-images.githubusercontent.com/74942852/229280982-a6959857-1808-449b-9d26-0097763df07a.png">

## 対応
srcの中にpagesを入れる
参考：https://nextjs-ja-translation-docs.vercel.app/docs/advanced-features/src-directory

**Comment by ko-shiro-hap** [comment]
移動した際にバグが生じていないかをしっかり確認する必要がありそうなので、多めにサイズを見積もる。
