### ISSUE TITLE
バーガーメニューのアイコン選定

### ISSUE THREAD

**Issue by bigdragon0610** [Anti-Pattern-Inc/anti-pattern-inc.github.io#205]
## 背景
モーダル内のアイコン (サービス、会社概要、ニュース、Hubの左にあるもの)が、それぞれのページと無関係なものになっている
<img width="745" alt="スクリーンショット 2023-04-01 19 21 39" src="https://user-images.githubusercontent.com/74942852/229280541-62880ae3-dbc0-42cb-ad71-007c9afb14f3.png">

## 対応
`src > components > Header.tsx` の `resources` でアイコンを設定している。このアイコンを変更する。

**Comment by ko-shiro-hap** [comment]
選定とは今現在で確定しているデザインはなく、選ぶところからが作業範囲なのか？
