### ISSUE TITLE
社員数の変更

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#216]
■現状
社員数
25名 (2021年8月1日時点)

■変更後
社員数
46名 (2023年4月1日時点)

**Comment by ko-shiro-hap** [comment]
竜大さんが、社員数はこれからも変わるからデータとして保管したいと言っていた記憶があるため確認する必要がある。
実装するとしたら、prismicに会社概要ページに対応するsliceを作成してデータを保管する。

**Comment by ko-shiro-hap** [comment]
@bigdragon0610 
[質問]
社員数はこれからも変わるからデータとして保管したいと竜大さんが言っていた記憶があるというのをあっちゃんから聞きました。
prismicに会社概要ページに対応するsliceを作成してデータを保管するという認識で合っていますか？

**Comment by bigdragon0610** [comment]
@ko-shiro-hap 
会社概要ページ用のcustomtypeを作成して、そこにデータを入れるようなイメージでした！

**Comment by ko-shiro-hap** [comment]
年2回くらいの更新のためそこまで手間をかけなくていい
