### ISSUE TITLE
prismicでコンテンツのプレビューをできるようにする

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#218]
<img width="1993" alt="スクリーンショット 2023-03-31 21 46 44" src="https://user-images.githubusercontent.com/8304640/229123994-31a379b5-f8d4-463a-afc5-4c851b0163b7.png">

今、localhostに繋ぐ設定になっていそうなので、正しい設定にしてコンテンツを公開前にプレビューできるようにしてほしい。

**Comment by ko-shiro-hap** [comment]
prismicのプレビュー機能の仕様について調べる。

**Comment by ko-shiro-hap** [comment]
参考サイト
https://prismic.io/docs/preview
