### ISSUE TITLE
サイトマップの分割及び自動生成

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#219]
こちらを参考に。
https://github.com/Anti-Pattern-Inc/saasus-marketing/issues/495

- トップページ/サービスページ/プライバシーポリシーなど
- News用
- Hub用
が生成されるように。

**Comment by ko-shiro-hap** [comment]
サイトマップについて調べる必要あり。理解していないため時間を多めに見積もる。

**Comment by atsuh1r0** [comment]
@kamibayasitaito @bigdragon0610 
msでは、envファイルでサイトURLの定義を行なっていますが、必要でしょうか。
