### ISSUE TITLE
デフォルトブランチを切り替え、protection rulesを設定する

### ISSUE THREAD

**Issue by ko-shiro-hap** [Anti-Pattern-Inc/anti-pattern-inc.github.io#226]
- デフォルトブランチがmasterになっているためdevelopに切り替える
- developにBranch protection rulesを設定する

**Comment by atsuh1r0** [comment]
@oztick139 
githubにsettingsの編集権限がないですが、付与していただけるでしょうか。権限の付与はできなければ、defalutブランチの変更をお願いしてもよろしいでしょうか。

**Comment by atsuh1r0** [comment]
@oztick139 
> developにBranch protection rulesを設定する
こちらの設定も行っていただく必要があり、竜大さんに相談したところ、
- developに直接pushできないようにする
- develop向けのプルリクエストはreviewerのチェックがない限りmergeできないようにする
の2点が必要だと思いました。この2点について変更していただけますでしょうか。また、これ以外にも必要な設定があれば、そちらもお願いします。

**Comment by oztick139** [comment]
@atsuh1r0 
saasus-marketingと同じ設定しておきました！

**Comment by atsuh1r0** [comment]
ありがとうございます。こちらのissueは完了とさせていただきます。
