### ISSUE TITLE
古いファイルを改修する

### ISSUE THREAD

**Issue by ko-shiro-hap** [Anti-Pattern-Inc/anti-pattern-inc.github.io#227]
- READMEが古いままである
古いワークフローファイルが残っている

**Comment by atsuh1r0** [comment]
@oztick139 
https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/blob/develop/.github/workflows/deploy.yml

このファイルが現在は使用されていないものだと思うのですが、削除してもよろしいでしょうか。

**Comment by atsuh1r0** [comment]
@oztick139 
現在、developにマージするごとにvercelが新しいドメインを発行しています。
saasusmarketingのように、developは固定のドメインでプレビューできればよいと考えているのですが、そのような認識でよろしいでしょうか。

その際、ドメインの設定は、小谷さんに相談しながら進めようと考えています。

**Comment by oztick139** [comment]
@atsuh1r0 
削除して大丈夫です！！

> saasusmarketingのように、developは固定のドメインでプレビューできればよいと考えているのですが、そのような認識でよろしいでしょうか。

はい！

**Comment by atsuh1r0** [comment]
@oztick139 
Gitpod系として、
.gitpod.Dockerfile
.gitpod.yml
がありますが、こちらもこのissueで削除するということでよろしいでしょうか。もしくは、別issueで対応でしょうか。
