### ISSUE TITLE
採用ページの実装

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#232]
■やりたいこと
採用ページの作成

■理由
アンチパターン社の理念に共感する人を採用するため、主に認知してくれた人がアンチパターン社のことをより理解するために活用するイメージ。なので情報量が少々多いページになる。

■デザインと素材
https://miro.com/app/board/uXjVPyQD2Ys=/?moveToWidget=3458764556275750245&cot=14
https://drive.google.com/drive/u/0/folders/1aksJuJoM-GhUC2dYgf3miOIQXkP0Pjx8

■その他対応
![Image](https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/assets/8304640/cef3f8bd-3bd6-415e-9886-03a5936928e6)
Wantedlyへのリンクからキャリページへのリンクに変更
文言は「キャリアページへ」

## タスク
- ヘッダーに「キャリア」を追加
  - レスポンシブ崩れがないか確認
- recruitセクションのWantedlyへのリンクからキャリページへのリンクに変更
- 採用ページ
  - ヒーロー
    - 画像を置く。
    - 文字を入れる。
  - 理論セクション
    - タイトルは中央
  - ビジネスコンセプトセクション
  - サービスセクション
    - /service と同じ
  - エンジニアブログ
    - エンジニアブログへの遷移(target _blank)
  - 社内環境セクション
    - アイコンの保存
  - 募集職種セクション
    - prismicとの連携
  - 採用フローセクション

**Comment by ko-shiro-hap** [comment]
@oztick139 
採用ページのmiroのアクセス権限がないので付与をお願いします。

**Comment by oztick139** [comment]
@ko-shiro-hap すいません、付与しました！

**Comment by ko-shiro-hap** [comment]
@oztick139 
試したのですがまだ入れませんでした。

**Comment by atsuh1r0** [comment]
質問内容
- 「価値観と行動指針の役割を確認する」ボタンを押したときの挙動がイメージできなかったので、教えていただきたいです。
![Image](https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/assets/106391644/44dc9b57-5f3f-45d2-8362-83f62ba4f072)
-

**Comment by oztick139** [comment]
@atsuh1r0 
「価値観と行動指針の役割を確認する」、こちらはMiroへのリンクを設置する予定なのでaタグ(別タグ)にしておいてください！
リンクはまだ準備中です！

> ビジネスコンセプトとサービスは、サービスページとまったく同じという認識で大丈夫でしょうか。

はい！
