### ISSUE TITLE
リファクタリング方針を決める

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#238]

**Comment by ko-shiro-hap** [comment]
[コーポレート]
- components内のページに依存しないコンポーネントが、現在componentsフォルダの直下に置かれてしまっているので、saasusのように用途ごとにフォルダを分けて管理したい。

[saasus]
- 本来ならGraphQLが型定義を行ってくれるはずらしいが、それが機能していないので直せれば直したい。(方針は想像できていない)
- TypeScriptの型のanyを定義し直す。

**Comment by oztick139** [comment]
@ko-shiro-hap 
* components内のページに依存しないコンポーネントが、現在componentsフォルダの直下に置かれてしまっているので、saasusのように用途ごとにフォルダを分けて管理したい。
* TypeScriptの型のanyを定義し直す。

一旦上記二つでISSUEにしておいて欲しいです！

**Comment by ko-shiro-hap** [comment]
@oztick139 
わかりました！
