### ISSUE TITLE
ヘッダーにエンジニアブログへのリンクを設置

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#251]
[サービス][会社概要][ニュース][Hub][ブログ][キャリア]
という並びにする

リンクはここ
https://tech.anti-pattern.co.jp/

**Comment by ko-shiro-hap** [comment]
ヘッダーにブログとキャリアを増やしたときにレスポンシブの調整が必要になるかもしれない
