### ISSUE TITLE
ITイベント情報の最新化

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#265]
https://anti-pattern.co.jp/hub/post/tech-conference-2023

イベント情報を最新化した上で、下記文言も調査日で最新化する
「2023年mm月dd日時点の情報です。最新情報は各イベント公式HP等をご覧ください。」

**Comment by ko-shiro-hap** [comment]
【追加】
ページネーションの実装に伴いprismicプレビュー時のパスも変更する必要があるため対応する。
