### ISSUE TITLE
node ver上げ対応(コーポレート)

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#281]
> Error: Node.js version 16.x has reached End-of-Life. Deployments created on or after 2024-02-06 will fail to build. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.

SaaSusの方でエラー出てたのでこっちもVercelでエラーが出てるかも？

**Comment by atsuh1r0** [comment]
こちらはnode18を使用しております
