### ISSUE TITLE
会社概要にISMSマークの掲載

### ISSUE THREAD

**Issue by oztick139** [Anti-Pattern-Inc/anti-pattern-inc.github.io#283]
CERTIFICATIONSに追加する

![Image](https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/assets/8304640/12646886-2b2f-4d69-bbd3-c455542796ec)

```[tasklist]
### Tasks
```

**Comment by minami-nogawa** [comment]
ISMSのロゴ
https://drive.google.com/file/d/1a6KFJFjiz5UYyfBQTOW28kgMr8reGcoB/view?usp=drive_link
