### ISSUE TITLE
会社概要ページの英語化対応

### ISSUE THREAD

**Issue by Sakinom** [Anti-Pattern-Inc/anti-pattern-inc.github.io#302]
## 関連リンク
https://anti-pattern.co.jp/company

## 関連するissue
- #297

**Comment by tatsu0731** [comment]
方針を決めて→共有→OKもらったら作業に入る

**Comment by tatsu0731** [comment]
# 会社情報の英語化対応方針のご相談
文言は基本的に開発側で英訳し、小笹さん及び野川さんをslackにてメンションし、文言の確認を行った後にメンターの方にレビューを依頼する形で進めていこうと考えております。

## 画像の対応
以下の画像の大元のリソース（miroかfigmaと思われる）を共有いただければ、開発側で日本語の文言を英語の文言に変えた上でサイトに表示する画像を差し替えることで対応可能
→元のリソースがなければ似たような画像を新たに作成することも可能
![Image](https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/assets/107157836/ce44ceb7-e35f-454d-88b9-452923578b39)

## 文言の対応
以下の「engineed　エンジニード」のように英語タイトルと日本語のタイトルの両方が表示されている箇所の対応をどうするか
→そのままでも問題ないが、カタカナを非表示にして英語だけにする方針の方が日本語がわからない方の混乱は防げると思われる（同じことが書かれていると認知できないため）
![Image](https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/assets/107157836/fbc16841-42ef-4db8-bc66-007888b13c74)

## SaaSus Consultingページについて
以下のセクションの「SERVICE SITE」リンクからアクセスした先のSaaSus Consultingページ( https://anti-pattern.co.jp/services/saasus-consulting )も今後英語化するのか
![Image](https://github.com/Anti-Pattern-Inc/anti-pattern-inc.github.io/assets/107157836/17d8d492-27c3-475a-80bf-a5a094af2698)
